# Name:Mateen Fatima
**Library:Numpy**
# Day 1

Numpy:
**Numpy stands for Numerical Python that is strong python Library used for Complex Computational Tasks,Data Analysis ,Numerical Operations.**


In [ ]:
pip install numpy


**Create Arrays** 1D

In [ ]:
import numpy as np
list1=[10,20,30,50]
array1=np.array(list1,dtype=str)
print(array1)
type(array1)

['10' '20' '30' '50']


numpy.ndarray

**2D Array:**

In [ ]:
import numpy as np
list1=[[10,20,30],[40,50,60],[70,80,90]]
array1=np.array(list1)
print(array1)
type(array1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


numpy.ndarray

**Create using Arrange/Range**

In [ ]:
import numpy as np
array1=np.arange(1,8)
print(array1)

[1 2 3 4 5 6 7]


# Create Using arange and shape


In [ ]:
import numpy as np
array1=np.arange(11,17).reshape(2,3)
print(array1)


[[11 12 13]
 [14 15 16]]


In [ ]:
array1=np.ones(4)
print(array1)

[1. 1. 1. 1.]


Create arrays that will have all ones

In [ ]:
array1=np.zeros(4)
print(array1)

[0. 0. 0. 0.]


Create arrays that will have all zeros


In [ ]:
array1.ndim   #Use to check dimension of array

1

In [ ]:
array1.itemsize # check item size in bytes

8

In [ ]:
array1.shape  # check shape like 1d,2d etc

(4,)

In [ ]:
array1.size  #check size of the array
array1.dtype #check data type

dtype('float64')



---



---

# Indexing

**Indexing is powerful way to manipulate data and accessing data from arrays.**


In [ ]:
import numpy as np
array1=[10,20,30,40]
print(array1[-1])

40


In [ ]:
array2=[[10,20,30,40],[50,60,70,80],[90,100,110,120]]
nparray=np.array(array2)
nparray.ndim  #check Dimension

2

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) # All reshapes
print(a)
print(a.reshape(6,2))
print(a.reshape(2,6))
print(a.reshape(1,12))
print(a.reshape(12,1))
print(a.reshape(4,3))
print(a.reshape(3,4))


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Indexing

print(a[1])
print(nparray[1,3])

2
80


In [ ]:

# Slicing used to access multiple elements from dataset
a = np.array([10,20,30,40,50,60])

print(a[1:4])
print(a[:3])
print(a[3:0:-1])
print(a[-4:-1])

[20 30 40]
[10 20 30]
[40 30 20]
[30 40 50]
